spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
      - id:  receptionistModule
        uri: http://localhost:8083/
        predicates:
        - Path=/receptionist/**
      - id: ownerModule
        uri: http://localhost:8081/
        predicates:
        - Path=/owner/**
      - id: managerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/manager/**
      - id: reservationModule
        uri: http://localhost:8084/
        predicates:
        - Path=/reservation/**
        
   
    
